
const TagTypes = {
   categories: "Categories",
   me: "Me",
   candidateOverview: "CandidateOverview",
   employerOverview: "EmployerOverview",
   appliedJobs: "AppliedJobs",
   appliedJobIds: "AppliedJobIds",
   recentAppliedJobs: "RecentAppliedJobs",
   favouriteJobs: "FavouriteJobs",
   favouriteJobIds: "FavouriteJobids",
   employerJobs: "EmployerJobs",
   jobs: "Jobs",
   findJob: "FindJob",
   candidates: "Candidates",
   candidate: "Candidate",
   favouriteCandidates: "FavouriteCandidates",
   job: "Job",
   recentPostedJobs: "RecentPostedJobs",
   subscriptions: "Subscriptions",
   subscriptionStatus: "SubscriptionStatus",
   recentBlogs: "RecentBlogs",
   blogs: "Blogs",
   blog: 'Blog',
   employerDetails: "EmployerDetails",
   applications: "Applications",
   applicationsByJobId: "ApplicationsByJobId",
   notifications: "Notifications",
   termsConditions: "TermsConditions",
   privacyPolicy: "PrivacyPolicy",
   aboutUs: "AboutUs",
   payments: "Payments",
   subscription_status: "Subscription_Status",
   categoryDropDown: "CategoryDropDown",
   subCategoryDropDown: "CategoryDropDown",
   blogCategoryDropDown: "BlogCategoryDropDown",
   plans: "Plans",
   employerStats: "EmployerStats",
   candidateStats: "CandidateStats"
}

export default TagTypes;